Add datagen tools
IntelLabs/OSCAR pull request #2
Opened 2023-05-05 16:59 UTC by lumurillo

The goal of this PR is to include a set of tools useful for the creation of COCO- or MOTS's compatible datasets, capturing the data from the CARLA simulator.

2023-05-11 05:17 UTC, dxoigmn reviewed
See comments. It might also be worth reviewing this paper and code: https://arxiv.org/abs/2305.00204

2023-05-11 05:17 UTC, dxoigmn commented on lib/oscar-datagen-toolkit/Makefile
I think replacing this with docker compose is probably the right call.

2023-05-19 15:26 UTC, lumurillo commented on lib/oscar-datagen-toolkit/Makefile
Working on adding docker compose support

2023-05-30 17:12 UTC, dxoigmn requested changes
See comments. Can you also change the headers to be BSD-3 license SPDX identifier?

2023-05-30 17:12 UTC, dxoigmn commented on .pre-commit-config.yaml
> +
Can you fix the newline issue

2023-05-30 17:12 UTC, dxoigmn commented on lib/oscar-datagen-toolkit/.env
> +G_ID=0
UID and GID are probably more standard linux names.

2023-05-31 00:26 UTC, lumurillo commented on lib/oscar-datagen-toolkit/.env
> +G_ID=0
Linux already has an env variable called `UID`, so I wanted to make this variables independent to that.

2023-08-07 17:08 UTC, lumurillo commented on lib/oscar-datagen-toolkit/README.md
> +- With Docker:
yes, agree

2023-08-07 17:09 UTC, lumurillo commented on lib/oscar-datagen-toolkit/README.md
> +- Manual installation
This was maybe a bad translation from spanish. I changed it to `Install from source code`

2023-08-07 17:10 UTC, lumurillo commented on lib/oscar-datagen-toolkit/README.md
> +
Added

2023-08-08 03:31 UTC, dxoigmn approved these changes
LGTM!

2023-08-08 18:03 UTC, merged